### ISSUE TITLE
Data layer separation for pyWWT visualization 

### ISSUE THREAD

**Issue by joaq-ram** [NASA-PDS/search-api-notebook#20]
Add a feature to pyWWT so that each lid is a separate data layer in the widget.

**Comment by tloubrieu-jpl** [comment]
We need to name the layer in an intuitive way which is not possible not with pyWWT on point layers but only on image layers. This requires a ticket on pyWWT to move forward with that.

**Comment by nutjob4life** [comment]
Request to actually name the applicable data layers based on the lid being examined. Requires some further work on the pywtt team. Peter (pywtt person) says "in order to do this we need to do some further development". Ticket in for Peter. Layer names to come. Created even more tickets on pwtt repo to be addressed. @Joaq-ram will assist. Switching data acquisition method to pds4 tools, which has useful methods to simplify code.

**Comment by tloubrieu-jpl** [comment]
We want to name the layer this requires a PR on the PYWWT code.

**Comment by joaq-ram** [comment]
Discovered ID parameter in data layers method and implemented feature to layers by lids and specified by file name. This feature is complete

**Comment by tloubrieu-jpl** [comment]
Fixed with PR https://github.com/NASA-PDS/search-api-notebook/pull/28/files
